# Generated by Django 4.2 on 2023-04-24 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_funcionario_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='time',
            field=models.CharField(default='', max_length=100, verbose_name='instagram'),
        ),
    ]
